services:
  postgres:
    image: postgres:16-alpine
    container_name: transparenta_ins_db
    environment:
      POSTGRES_USER: ins_tempo
      POSTGRES_PASSWORD: ins_tempo
      POSTGRES_DB: ins_tempo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    shm_size: 256mb
    command: >
      postgres
      -c max_locks_per_transaction=256
      -c shared_buffers=512MB
      -c effective_cache_size=1536MB
      -c work_mem=16MB
      -c maintenance_work_mem=256MB
      -c wal_buffers=16MB
      -c max_wal_size=2GB
      -c min_wal_size=512MB
      -c checkpoint_completion_target=0.9
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c max_parallel_workers_per_gather=2
      -c max_parallel_workers=4
      -c max_worker_processes=4
      -c default_statistics_target=200
      -c huge_pages=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ins_tempo"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
